mergeConflictCheck:
  commentTitle: 'Kindly fix the conflicts'
  label: 'merge conflict'
  state: 'dirty'

fileMissingCheck:
  commentTitle: 'Changelog file missing'
  label: 'Missing Changelog'
  path: 'CHANGELOG.md'