name: Outdated npm check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - name: npm outdated
      run: |
        npm outdated
      env:
        CI: false

