name: npm check outdated and audit.

on: [push]

jobs:
  outdated_and_audit:

    runs-on: ubuntu-latest

    steps:
    - name: npm outdated
      run: |
        npm outdated | node parser.js
    - name: npm audit
      run: |
        npm audit | node parser.js
      env:
        CI: false

