name: Outdated CI.

on: [push]

jobs:
  outdated:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm-outdated
      id: outdated
      run: |
        npm outdated --json | node parser-outdated.js
      env:
        CI: false

