name: Check npm outdated CI

on: push

jobs:
  job_3:
    name: Display results
    runs-on: ubuntu-latest
    steps:
      - name: Print the final result
        shell: bash
        run: |
          value=npm outdated
          echo The result is $value


