name: Outdated npm check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - name: npm install, build, and test
      run: |
        npm outdated > results.html
      env:
        CI: false

