name: Test CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - name: npm lint
      run: |
        npm install
        npm run test
        echo Add other actions to build..
      env:
        CI: true
